#version 430 core
#pragma shader_stage(compute)

#define TX_OPENGL 1

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

const float INV_PI     = 0.31830988618379067;
const float INV_TWO_PI = 0.15915494309189533;
const float TWO_PI     = 6.28318530717958648;

const float EPS = 0.001;
const float INF = 1000000000;

vec2 Stack[64];
int StackPtr = 0;

#include "structs.comp"
#include "uniforms.comp"
#include "random.comp"
#include "transforms.comp"
#include "intersection.comp"
#include "sampling.comp"
#include "bsdf.comp"

vec4 PathTrace(in Ray ray, out vec3 albedo, out vec3 normal, out float z)
{
    albedo = normal = vec3(0);
    z = 0;

    vec3 throughput = vec3(1);
    vec3 radiance = vec3(0);

    bool isSampled = false;
    for (uint depth = 0; depth <= MaxDepth; depth++)
    {
        CollisionManifold manifold;
        if (!FindIntersection(ray, depth == 0 ? Camera.ZNear : EPS, depth == 0 ? Camera.ZFar : INF, manifold))
        {
            vec4 envColPdf = GetEnvironment(ray);
            float misWeight = depth > 0 ? PowerHeuristic(1, envColPdf.w) : 1;
            radiance += misWeight * envColPdf.rgb * throughput;

            if (!isSampled)
            {
                albedo = radiance;
                normal = -ray.Direction;
                z = Camera.ZFar;
            }

            return vec4(radiance, !isSampled && Environment.Transparent ? 0 : 1);
        }

        Material material = GetMaterial(manifold);

        if (BSDF(ray, throughput, radiance, manifold))
        {
            ray.InvDirection = 1 / ray.Direction;
            if (!isSampled)
            {
                albedo = throughput;
                normal = manifold.Normal;
                z += manifold.Depth;
            }

            isSampled = true;
        }
        else
        {
            ray.Origin = manifold.Point;
            if (!isSampled)
            {
                z += manifold.Depth;
            }
        }

        // Russian roulette
        if (RussianRouletteDepth > 0 && depth >= RussianRouletteDepth)
        {
            float q = min(max(throughput.x, max(throughput.y, throughput.z)) + 0.001, 0.95);
            if (RandomValue() > q)
            {
                break;
            }

            throughput /= q;
        }
    }

    return vec4(radiance, 1);
}

void main()
{
    if (any(lessThan(TexelCoord, FramePosition)) || any(lessThanEqual(FramePosition + FrameSize, TexelCoord)))
    {
        return;
    }

    vec2 coord = (UV - vec2(.5)) * vec2(1, float(Size.y) / Size.x) * 2 * tan(Camera.FOV * .5);
    Ray ray = Ray(Camera.Position, normalize(Camera.Forward + CameraRight * coord.x + Camera.Up * coord.y), vec3(0));
    JitterRay(ray);

    vec3 albedo, normal;
    float depth;
    vec4 accumColor = PathTrace(ray, albedo, normal, depth) + imageLoad(AccumulatorImage, TexelCoord);

    if (SampleCount == 0)
    {
        imageStore(AlbedoImage, TexelCoord, vec4(albedo, 1));
        imageStore(NormalImage, TexelCoord, NormalToColor(normal));
        imageStore(DepthImage, TexelCoord, DepthToColor(depth));
    }

    imageStore(AccumulatorImage, TexelCoord, accumColor);
}
