layout(rgba32f, binding=0)           uniform image2D AccumulatorImage;
layout(rgba32f, binding=1) writeonly uniform image2D AlbedoImage;
layout(rgba32f, binding=2) writeonly uniform image2D NormalImage;
layout(r32f,    binding=3) writeonly uniform image2D DepthImage;
layout(rgba32f, binding=4) writeonly uniform image2D ToneMapImage;

layout(binding=0) uniform sampler2D EnvironmentTexture;
layout(binding=1) uniform sampler2D EnvironmentCDFTexture;
layout(binding=2) uniform sampler2DArray Textures;

layout(std430, binding=0) readonly buffer VertexSSBO
{
    Vertex Vertices[];
};

layout(std430, binding=1) readonly buffer TriangleSSBO
{
    Triangle Triangles[];
};

layout(std430, binding=2) readonly buffer MeshSSBO
{
    Mesh Meshes[];
};

layout(std430, binding=3) readonly buffer MeshInstanceSSBO
{
    MeshInstance MeshInstances[];
};

layout(std430, binding=4) readonly buffer MaterialSSBO
{
    Material Materials[];
};

layout(std430, binding=5) readonly buffer BlasSSBO
{
    Node BLAS[];
};

layout(std430, binding=6) readonly buffer TlasSSBO
{
    Node TLAS[];
};

layout(std140, binding=0) uniform CameraUBO
{
    Cam Camera;
};

layout(std140, binding=1) uniform EnvironmentUBO
{
    Env Environment;
};

layout(std140, binding=2) uniform ParamsUBO
{
    ivec2 FramePosition;
    ivec2 FrameSize;
    uint SampleCount;
    uint MaxDepth;
    uint RussianRouletteDepth;
    bool OnlyToneMapping;
    uint ToneMapMode;
    float Gamma;
};

ivec2 Size = imageSize(AccumulatorImage);
ivec2 EnvironmentSize = textureSize(EnvironmentTexture, 0);
ivec2 TexelCoord = ivec2(gl_GlobalInvocationID.xy) + FramePosition;
vec2 UV = vec2(TexelCoord) / Size;
vec3 CameraRight = cross(Camera.Forward, Camera.Up);

float Luminance(vec3 c)
{
    return 0.212671 * c.x + 0.715160 * c.y + 0.072169 * c.z;
}

vec4 GetEnvironment(in Ray ray)
{
    vec3 direction = Environment.Rotation * ray.Direction;
    float theta = acos(direction.y);
    
    float v = theta * INV_PI;
    float u = atan(direction.z, direction.x) * INV_TWO_PI + 0.5;

    vec3 color = texture(EnvironmentTexture, vec2(u, v)).rgb * Environment.Intensity;
    float pdf = Luminance(color) / Environment.CdfTotal;
    return vec4(color, pdf * EnvironmentSize.x * EnvironmentSize.y * INV_TWO_PI * INV_PI / sin(theta));
}

Material GetMaterial(inout CollisionManifold manifold)
{
    Material material = Materials[manifold.MaterialId];

    if (material.AlbedoTextureId >= 0)
    {
        material.AlbedoColor *= texture(Textures, vec3(manifold.TextureCoordinate, material.AlbedoTextureId));
    }

    if (material.MetalnessTextureId >= 0)
    {
        material.Metalness *= texture(Textures, vec3(manifold.TextureCoordinate, material.MetalnessTextureId)).b;
    }

    if (material.RoughnessTextureId >= 0)
    {
        material.Roughness *= texture(Textures, vec3(manifold.TextureCoordinate, material.RoughnessTextureId)).g;
    }

    material.EmissionColor *= material.EmissionStrength;
    if (material.EmissionTextureId >= 0)
    {
        material.EmissionColor *= texture(Textures, vec3(manifold.TextureCoordinate, material.EmissionTextureId)).rgb;
    }

    if (material.NormalTextureId >= 0)
    {
        vec3 texNormal = texture(Textures, vec3(manifold.TextureCoordinate, material.NormalTextureId)).rgb;
        texNormal.y = 1 - texNormal.y;
        texNormal = normalize(texNormal * 2 - 1);
        manifold.Normal = normalize(manifold.Tangent * texNormal.x + manifold.Bitangent * texNormal.y + manifold.Normal * texNormal.z);
    }

    if (!manifold.IsFrontFace)
    {
        manifold.Normal *= -1;
    }

    return material;
}
